/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author jhudy
 */
public class Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Cuenta
     */
    public Cuenta() {
        initComponents();
    }

    public ButtonGroup getBtnGroupProceso() {
        return btnGroupProceso;
    }

    public void setBtnGroupProceso(ButtonGroup btnGroupProceso) {
        this.btnGroupProceso = btnGroupProceso;
    }

    public JButton getBtnRegistrarProceso() {
        return btnRegistrarProceso;
    }

    public void setBtnRegistrarProceso(JButton btnRegistrarProceso) {
        this.btnRegistrarProceso = btnRegistrarProceso;
    }

    public JLabel getLblCuentadeUsuario() {
        return lblCuentadeUsuario;
    }

    public void setLblCuentadeUsuario(JLabel lblCuentadeUsuario) {
        this.lblCuentadeUsuario = lblCuentadeUsuario;
    }

    public JLabel getLblNombreUsu() {
        return lblNombreUsu;
    }

    public void setLblNombreUsu(JLabel lblNombreUsu) {
        this.lblNombreUsu = lblNombreUsu;
    }

    public JLabel getLblSaldoUsu() {
        return lblSaldoUsu;
    }

    public void setLblSaldoUsu(JLabel lblSaldoUsu) {
        this.lblSaldoUsu = lblSaldoUsu;
    }

    public JRadioButton getRbtnDeposito() {
        return rbtnDeposito;
    }

    public void setRbtnDeposito(JRadioButton rbtnDeposito) {
        this.rbtnDeposito = rbtnDeposito;
    }

    public JRadioButton getRbtnRetiro() {
        return rbtnRetiro;
    }

    public void setRbtnRetiro(JRadioButton rbtnRetiro) {
        this.rbtnRetiro = rbtnRetiro;
    }

    public JTextField getTxtValorProcesar() {
        return txtValorProcesar;
    }

    public void setTxtValorProcesar(JTextField txtValorProcesar) {
        this.txtValorProcesar = txtValorProcesar;
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupProceso = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnRegistrarProceso = new javax.swing.JButton();
        lblCuentadeUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        lblNombreUsu = new javax.swing.JLabel();
        lblSaldoUsu = new javax.swing.JLabel();
        txtValorProcesar = new javax.swing.JTextField();
        rbtnRetiro = new javax.swing.JRadioButton();
        rbtnDeposito = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 270, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saldo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 79, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 136, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, 10));

        btnRegistrarProceso.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrarProceso.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnRegistrarProceso.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProceso.setText("Registrar");
        jPanel1.add(btnRegistrarProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 89, 34));

        lblCuentadeUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jPanel1.add(lblCuentadeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 220, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cuenta de Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 126, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 221, -1, -1));

        lblNombreUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblNombreUsu.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblNombreUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 90, 20));

        lblSaldoUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblSaldoUsu.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblSaldoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, 20));

        txtValorProcesar.setBackground(new java.awt.Color(0, 102, 102));
        txtValorProcesar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtValorProcesar.setForeground(new java.awt.Color(0, 0, 0));
        txtValorProcesar.setBorder(null);
        jPanel1.add(txtValorProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 80, 20));

        rbtnRetiro.setBackground(new java.awt.Color(0, 153, 153));
        btnGroupProceso.add(rbtnRetiro);
        rbtnRetiro.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rbtnRetiro.setForeground(new java.awt.Color(0, 0, 0));
        rbtnRetiro.setText("Retiro");
        jPanel1.add(rbtnRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 100, 30));

        rbtnDeposito.setBackground(new java.awt.Color(0, 153, 153));
        btnGroupProceso.add(rbtnDeposito);
        rbtnDeposito.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rbtnDeposito.setForeground(new java.awt.Color(0, 0, 0));
        rbtnDeposito.setText("Deposito");
        jPanel1.add(rbtnDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("opción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 156, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Cuenta().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupProceso;
    private javax.swing.JButton btnRegistrarProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblCuentadeUsuario;
    private javax.swing.JLabel lblNombreUsu;
    private javax.swing.JLabel lblSaldoUsu;
    private javax.swing.JRadioButton rbtnDeposito;
    private javax.swing.JRadioButton rbtnRetiro;
    private javax.swing.JTextField txtValorProcesar;
    // End of variables declaration//GEN-END:variables
}
