/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author jhudy
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    public JButton getBtnRegistrarNuevoUsu() {
        return btnRegistrarNuevoUsu;
    }

    public void setBtnRegistrarNuevoUsu(JButton btnRegistrarNuevoUsu) {
        this.btnRegistrarNuevoUsu = btnRegistrarNuevoUsu;
    }

    public JLabel getLblRegistroUsuario() {
        return lblRegistroUsuario;
    }

    public void setLblRegistroUsuario(JLabel lblRegistroUsuario) {
        this.lblRegistroUsuario = lblRegistroUsuario;
    }

    public JTextField getTxtUsuarioNuevo() {
        return txtUsuarioNuevo;
    }

    public void setTxtUsuarioNuevo(JTextField txtUsuarioNuevo) {
        this.txtUsuarioNuevo = txtUsuarioNuevo;
    }

    public JPasswordField getTxtpssClaveNueva() {
        return txtpssClaveNueva;
    }

    public void setTxtpssClaveNueva(JPasswordField txtpssClaveNueva) {
        this.txtpssClaveNueva = txtpssClaveNueva;
    }

    public JPasswordField getTxtpssClaveNuevaRepetir() {
        return txtpssClaveNuevaRepetir;
    }

    public void setTxtpssClaveNuevaRepetir(JPasswordField txtpssClaveNuevaRepetir) {
        this.txtpssClaveNuevaRepetir = txtpssClaveNuevaRepetir;
    }

    public JTextField getTxtsaldoinicial() {
        return txtsaldoinicial;
    }

    public void setTxtsaldoinicial(JTextField txtsaldoinicial) {
        this.txtsaldoinicial = txtsaldoinicial;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtpssClaveNueva = new javax.swing.JPasswordField();
        txtUsuarioNuevo = new javax.swing.JTextField();
        btnRegistrarNuevoUsu = new javax.swing.JButton();
        lblRegistroUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtpssClaveNuevaRepetir = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsaldoinicial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 260, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 274, 270, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese clave:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 130, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, 10));

        txtpssClaveNueva.setBackground(new java.awt.Color(0, 102, 102));
        txtpssClaveNueva.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtpssClaveNueva.setForeground(new java.awt.Color(0, 0, 0));
        txtpssClaveNueva.setBorder(null);
        jPanel1.add(txtpssClaveNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 90, 20));

        txtUsuarioNuevo.setBackground(new java.awt.Color(0, 102, 102));
        txtUsuarioNuevo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtUsuarioNuevo.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioNuevo.setBorder(null);
        jPanel1.add(txtUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 90, 20));

        btnRegistrarNuevoUsu.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrarNuevoUsu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnRegistrarNuevoUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarNuevoUsu.setText("Registrar");
        jPanel1.add(btnRegistrarNuevoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, 34));

        lblRegistroUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jPanel1.add(lblRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro de Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 130, 10));

        txtpssClaveNuevaRepetir.setBackground(new java.awt.Color(0, 102, 102));
        txtpssClaveNuevaRepetir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtpssClaveNuevaRepetir.setForeground(new java.awt.Color(0, 0, 0));
        txtpssClaveNuevaRepetir.setBorder(null);
        jPanel1.add(txtpssClaveNuevaRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Repetir clave:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Saldo inicial:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtsaldoinicial.setBackground(new java.awt.Color(0, 102, 102));
        txtsaldoinicial.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        txtsaldoinicial.setForeground(new java.awt.Color(0, 0, 0));
        txtsaldoinicial.setBorder(null);
        jPanel1.add(txtsaldoinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarNuevoUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblRegistroUsuario;
    private javax.swing.JTextField txtUsuarioNuevo;
    private javax.swing.JPasswordField txtpssClaveNueva;
    private javax.swing.JPasswordField txtpssClaveNuevaRepetir;
    private javax.swing.JTextField txtsaldoinicial;
    // End of variables declaration//GEN-END:variables
}
